### PR TITLE
Fix dataSetToDataFrame

### LINKED ISSUE #603: DataSet: add "name" to print
Second line of the print function should print the name of the data set.

### PR DESCRIPTION
**Pull request by PavelBal**
Fixes #603; #604

### CODE REVIEW

File: R/utilities-data-set.R [hunk 1]
```diff
@@ -55,38 +55,64 @@ saveDataSetToPKML <- function(dataSet, filePath) {
...
-  yUnit <- unlist(mapply(.makeDataFrameColumn, dataSets, "yUnit"))
-  yErrorUnit <- as.character(unlist(mapply(.makeDataFrameColumn, dataSets, "yErrorUnit")))
-  xDimension <- unlist(mapply(.makeDataFrameColumn, dataSets, "xDimension"))
-  yDimension <- unlist(mapply(.makeDataFrameColumn, dataSets, "yDimension"))
-  yErrorType <- as.character(unlist(mapply(.makeDataFrameColumn, dataSets, "yErrorType")))
-  yMolWeight <- unlist(mapply(.makeDataFrameColumn, dataSets, "molWeight"))
-  xValue <- unlist(mapply(.makeDataFrameColumn, dataSets, "xValues"))
-  yValue <- unlist(mapply(.makeDataFrameColumn, dataSets, "yValues"))
-  yErrorValues <- unlist(mapply(.makeDataFrameColumn, dataSets, "yErrorValues"))
+  name <- unlist(lapply(dataSets, function(x) {
```
Comment (PavelBal) [inline R/utilities-data-set.R:70]: mapply and sapply and so produce weird results sometimes (in case of data sets loaded from excel the output was a matrix, in the case of manually created data sets it was a vector...), `lapply` is the only function that _always_ will return a list, so lets use it where possible.

Adding `use.naames = FALSE` to `unlist` speeds up the whole thing and should be used when we do not need a named list.

Comment (PavelBal) [reply R/utilities-data-set.R:70]: @hannaei FYI

File: R/utilities-data-set.R [hunk 2]
```diff
@@ -55,38 +55,64 @@ saveDataSetToPKML <- function(dataSet, filePath) {
...
+    .makeDataFrameColumn(x, "yErrorValues")
+  }), use.names = FALSE)
+  lloq <- unlist(lapply(dataSets, function(x) {
+    .makeDataFrameColumn(x, "LLOQ")
+  }), use.names = FALSE)
 
   df <- data.frame(
-    name, xValue, yValue, yErrorValues, xDimension, xUnit, yDimension,
-    yUnit, yErrorType, yErrorUnit, yMolWeight
+    name, xValues, yValues, yErrorValues, xDimension, xUnit, yDimension,
```
Comment (PavelBal) [inline R/utilities-data-set.R:108]: Renamed column names (using plural) and added a LLOQ column.

Comment (msevestre) [reply R/utilities-data-set.R:108]: if feels like you could write a method
```
makeColums <- function(dataSets, columnName) {
  unlist(lapply(dataSet, function(x){
.makeDatqaFrameColumn(x, columnsName)
}
}

```
or sthg like this

**Review by msevestre — COMMENTED** [review]
see suggestion to avoid code duplicatin

**Comment by PavelBal** [comment]
@msevestre done.
Also the build is not failing any more.
