### PR TITLE
Fixes #416 create population should not return derived parameters

### LINKED ISSUE #416: CreatePopulation should not return derived parameters
@Yuri05 The implementation of `createPopulation` in R `https://docs.open-systems-pharmacology.org/working-with-r/r-introduction#creating-populations` follows exactly the one that was previously available in Matlab.

I think this is a mistake. We are returning distributed parameters but also derived parameters such as blood flow etc. If one updates the values for blood flow spec, the blood flows are therefore not updated and one gets wrong results.

I think this should be amended. It should be done in PKSim but this would require a new version. I'd suggest to patch ospsuite-r instead to remove all derived parameters

### PR DESCRIPTION
**Pull request by msevestre**
The population returned by createPopulation also contains formula parameters which is not the expected behavior
This workaround fixes the issue by returning a list with two objects
1/a population (what was returned before)
2/a list of path values to see the value of all derived parameters at TIME OF CREATION of the population

Updating the population object will obviously not update the derived parameters but at least we have a good separation of concern

### CODE REVIEW

File: R/create-population.R [hunk 1]
```diff
@@ -3,15 +3,50 @@
...
+  else {
+    # create an individual with similar properites Species and population. WEIGHT AND AGE DO NOT MATTER as long as we can create an invidiual
+    individualCharacteristics <- ospsuite::createIndividualCharacteristics(
+      species = populationCharacteristics$species,
+      population = populationCharacteristics$population,
+      weight = populationCharacteristics$weightMin
+    )
+  }
+
+  individual <- createIndividual(individualCharacteristics = individualCharacteristics)
```
Comment (msevestre) [inline R/create-population.R:39]: This code is required here to retrieve the list of derived parameters from the individual. We therefor make  sure that everything is consistent

File: vignettes/create-run-population.Rmd [hunk 2]
```diff
@@ -52,7 +52,8 @@ populationCharacteristics <- createPopulationCharacteristics(
 print(populationCharacteristics)
 
 # Create population from population characteristics
-myPopulation <- createPopulation(populationCharacteristics = populationCharacteristics)
+result <- createPopulation(populationCharacteristics = populationCharacteristics)
+myPopulation <- result$population
```
Comment (msevestre) [inline vignettes/create-run-population.Rmd:56]: All: This is the change in API. Instead of getting a population object directly, one needs to get the $population object from the result.

**Comment by msevestre** [comment]
and + Coverage    80.23%   87.34%   +7.11%      :)

File: R/create-population.R [hunk 3]
```diff
@@ -3,15 +3,50 @@
...
+    )
+  }
+  else {
+    # create an individual with similar properites Species and population. WEIGHT AND AGE DO NOT MATTER as long as we can create an invidiual
+    individualCharacteristics <- ospsuite::createIndividualCharacteristics(
+      species = populationCharacteristics$species,
+      population = populationCharacteristics$population,
+      weight = populationCharacteristics$weightMin
+    )
+  }
```
Comment (Yuri05) [inline R/create-population.R:37]: why do we need this differentiation between human and not-human here?
`individualCharacteristics `defined as in lines 24-27 would work also for animals, or not?

File: vignettes/create-run-population.Rmd (hunk 2 above)
Comment (Yuri05) [reply vignettes/create-run-population.Rmd:56]: Why not just extend the population R class with the `DerivedParametersPaths `and `DerivedParametersValues `instead?

Comment (msevestre) [reply vignettes/create-run-population.Rmd:56]: because this would mean changing everything in core. AT the moment, a population is what is being varied. The concept of derived etc.. does not exist. It is also possible to override a formula with some values so this would create a serious headache. I don't think this is something we would want to do

File: R/create-population.R (hunk 3 above)
Comment (msevestre) [reply R/create-population.R:37]: maybe but I do not want ot create a 70kg mouse. I'd rather use the default from the DB.

File: vignettes/create-run-population.Rmd (hunk 2 above)
Comment (Yuri05) [reply vignettes/create-run-population.Rmd:56]: I disagree.
You could just add `derivedParameters` property to the **population R6-class only** (the property would be **read/write for now**. As soon as the core is adjusted, it can be made read-only). 
So instead of `return(list(population = population, derivedParameters = derivedParameters))` I would just do
```
population.derivedParameters = derivedParameters
return population
```
Then no API change now (and no API change in the future when the core is adjusted).

Comment (msevestre) [reply vignettes/create-run-population.Rmd:56]: We are going to have to agree to disagree. While this would work, for the population object, this is also the object that is being passed to runSimulation. 
Or do you suggest to create a separate list in the population object?

Comment (msevestre) [reply vignettes/create-run-population.Rmd:56]: >population.derivedParameters = derivedParameters

I see. The problem with this is that we have to add much more code. For example, we need to verify that a parameter is not in the two lists, etc. 

For simple consistency, because createIndividual returns a list with two items, I think createPopulation should do the same

Comment (msevestre) [reply vignettes/create-run-population.Rmd:56]: Let's discuss it tomorrow. I don't undersnad what readonly means for example. one should be allowed to overwrite this stuff.
So let's think about what we would like to have from an API point of view and we can update

File: R/create-individual.R [hunk 4]
```diff
@@ -90,7 +90,7 @@ createIndividualCharacteristics <- function(
   validateIsString(species)
   validateIsString(population, nullAllowed = TRUE)
   validateIsString(gender, nullAllowed = TRUE)
-  validateIsNumeric(weight)
+  validateIsNumeric(weight, nullAllowed = TRUE)
```
Comment (msevestre) [inline R/create-individual.R:93]: @Yuri05 In fact it was not required indeed. MeanBW is used in this case

File: R/create-population.R (hunk 3 above)
Comment (msevestre) [reply R/create-population.R:35]: age is required for human however.

File: R/create-population.R [hunk 5]
```diff
@@ -3,15 +3,64 @@
...
+
+  individual <- createIndividual(individualCharacteristics = individualCharacteristics)
+
+  derivedParameters <- list()
+
+  # Even though those parameters are derived parmaeters, we keep them in the population for consistency purpose with the PKSim export.
+  standardDerivedParametersToKeep <- c(StandardPath$Weight, StandardPath$BMI, StandardPath$BSA)
+
+  for (derivedParameterPath in individual$derivedParameters$paths) {
+    if (derivedParameterPath %in% c(StandardPath$Weight, StandardPath$BMI, StandardPath$BSA)) {
```
Comment (msevestre) [inline R/create-population.R:45]: Keeping those guys

File: R/create-population.R [hunk 6]
```diff
@@ -3,15 +3,64 @@
...
+    }
+
+    if (population$has(derivedParameterPath)) {
+      derivedParameters[[derivedParameterPath]] <- population$getParameterValues(derivedParameterPath)
+      population$remove(derivedParameterPath)
+    }
+  }
+
+  # other parameters to remvove that should not have been exported in the first place
+  standardDistributedParametersToRemove <- c(toPathString(StandardContainer$Organism, "MeanBW"), toPathString(StandardContainer$Organism, "MeanHeight"))
```
Comment (msevestre) [inline R/create-population.R:56]: Also removing this. 
Man the ONE CODE THAT I DID NOT CHECK from the old matlab toolbox is full of crap. Crazy

File: R/create-population.R (hunk 3 above)
Comment (PavelBal) [reply R/create-population.R:35]: The requirement for age has been added at some point - it was possible to create an individual without specifying the age. Why is it mandatory now?

Comment (msevestre) [reply R/create-population.R:35]: It's been like that in PKSim.Matlab for a while.  What is the use case of creating an individual without knowing the age?

File: R/create-population.R (hunk 5 above)
Comment (PavelBal) [inline R/create-population.R:45]: Why not `%in% standardDerivedParametersToKeep`? You are repeating the code. Also, where is `standardDerivedParametersToKeep` actually used?

File: vignettes/create-run-population.Rmd (hunk 2 above)
Comment (PavelBal) [reply vignettes/create-run-population.Rmd:56]: > > population.derivedParameters = derivedParameters
> 
> I see. The problem with this is that we have to add much more code. For example, we need to verify that a parameter is not in the two lists, etc.
> 
> For simple consistency, because createIndividual returns a list with two items, I think createPopulation should do the same

But `createIndividual` returns two lists of parameters. `createPopulation` would return a population-object and a list of parameters - rather inconvenient for me.

File: R/create-population.R (hunk 3 above)
Comment (PavelBal) [reply R/create-population.R:35]: Creating a "standard" individual :) It did definitely work without specifying the age, I had it in one of our scripts and had to update it yesterday as I used it for the first time with the latest release of osps-R.

File: vignettes/create-run-population.Rmd (hunk 2 above)
Comment (msevestre) [reply vignettes/create-run-population.Rmd:56]: Why is it iconvenenient? Those derived parmaeters are for "info" only and are stale as soon as you work with the population parameters (in a way that would change those derived parameters). I think that this is the best way to not have inconsistencies

File: R/dot-net-wrapper.R [hunk 7]
```diff
@@ -21,6 +21,10 @@ DotNetWrapper <- R6::R6Class(
     #' @return A new `DotNetWrapper` object.
     initialize = function(ref) {
       self$ref <- ref
+    },
+    finalize = function() {
+      # maybe dispose should be called to if available.
+      self$ref <- NULL
```
Comment (msevestre) [inline R/dot-net-wrapper.R:27]: @Yuri05 As discussed :)

File: appveyor.yml [hunk 8]
```diff
@@ -12,7 +12,7 @@ install:
   - git submodule update --init --recursive
 
 environment:
-  app_version: "9.0"
+  app_version: "9.1"
```
Comment (msevestre) [inline appveyor.yml:15]: Also bump version to 9.1 so that we can load PKSim correctly

**Comment by msevestre** [comment]
@all. I have updated the version to 9.1 to be compatible with the latest suite coming out soon. That way, we are consistent if people stick with 9.0

File: R/create-population.R (hunk 5 above)
Comment (PavelBal) [reply R/create-population.R:45]: @msevestre I think this has not been resolved...
