### PR TITLE
Fixes #133 getXXX: "stopIfNotFound"

### LINKED ISSUE #133: getXXX: "stopIfNotFound"
I propose to add the option to the `getParameter/getContainer` etc. to stop if no entity can be found under the supplied path. 
The argument `stopIfNotFound` is set to `FALSE` by default, and the functions return `NULL` or an empty list. If `stopIfNotFound == TRUE`, the function stops with an error.

I think it is a useful feature as most of the time I definitely **want** to get that parameter/container, and if it is not found it means that the provided path is wrong.

### PR DESCRIPTION
**Pull request by PavelBal**
-implement stopIfNotFound (https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/173 and https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/133 https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/179)
-Change default number of cores to (max - 1) (https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/200)

### CODE REVIEW

File: NAMESPACE [hunk 1]
```diff
@@ -3,6 +3,7 @@
 export(CompareBy)
 export(ContainerType)
 export(QuantityType)
+export(SimulationRunOptions)
```
Comment (PavelBal) [inline NAMESPACE]: This fixes https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/205

File: R/simulation-results.R [hunk 2]
```diff
@@ -39,10 +39,15 @@ SimulationResults <- R6::R6Class("SimulationResults",
       rClr::clrCall(self$ref, "HasResultsFor", as.integer(individualId))
     },
 
-    getValuesByPath = function(path, individualIds) {
+    getValuesByPath = function(path, individualIds, stopIfNotFound = TRUE) {
       validateIsNumeric(individualIds)
       individualIds <- c(individualIds)
       values <- rClr::clrCall(self$ref, "AllValuesFor", path, as.integer(individualIds))
+
+      if (unique(is.nan(values)) && stopIfNotFound) {
```
Comment (PavelBal) [inline R/simulation-results.R]: Assuming that rClr call returns NaNs if the results is not present.

File: R/utilities-entity.R [hunk 3]
```diff
@@ -24,13 +24,13 @@ CompareBy <- enum(c(
 #' sim <- loadSimulation(simPath)
 #'
 #' parameters <- c(
-#'   getParameter(toPathString(c("Organism", "Liver", "Pericentral", "Volume")), sim),
-#'   getParameter(toPathString(c("Organism", "Liver", "Pericentral", "Volume")), sim),
-#'   getParameter(toPathString(c("Organism", "Liver", "Pericentral", "Weight (tissue)")), sim)
+#'   getParameter(toPathString(c("Organism", "Liver", "Volume")), sim),
```
Comment (PavelBal) [inline R/utilities-entity.R]: I had some pain here figuring out why the example would not run! The simple simulation is just too simple :)

File: R/simulation-results.R (hunk 2 above)
Comment (msevestre) [reply R/simulation-results.R]: Nope. Check the tests. It returns NA

File: R/utilities-container.R [hunk 4]
```diff
@@ -38,21 +38,28 @@ getAllContainersMatching <- function(paths, container) {
...
 #' @export
-getContainer <- function(path, container) {
+getContainer <- function(path, container, stopIfNotFound = TRUE) {
   containers <- getAllContainersMatching(path, container)
   if (length(containers) > 1) {
     stop(messages$errorGetEntityMultipleOutputs(path, container))
   }
 
   if (length(containers) == 0) {
+    if (stopIfNotFound) {
```
Comment (msevestre) [inline R/utilities-container.R]: We have the same exact lines 
```
if (length(containers) > 1) {
    stop(messages$errorGetEntityMultipleOutputs(path, container))
  }

  if (length(containers) == 0) {
    if (stopIfNotFound) {
      stop(messages$errorEntityNotFound(path, container))
    }
    return(NULL)
  }
``` 
3 times.

Can we refactor?

File: R/simulation-results.R (hunk 2 above)
Comment (PavelBal) [reply R/simulation-results.R]: No, it returns NaN and is converted to NA in the next step. The check for `stopIfNotFound` occurs before that.

File: R/utilities-container.R (hunk 4 above)
Comment (PavelBal) [reply R/utilities-container.R]: I have moved the `getXXX ` and `getAllXXXMatching` to utilities-entity.

File: R/simulation-results.R (hunk 2 above)
Comment (msevestre) [reply R/simulation-results.R]: oh I did not see that this check was is IN the object itself. Is there a reason why you don't do the check in the calling method (e.g. the utilities?)

File: R/utilities-simulation-results.R [hunk 5]
```diff
@@ -63,10 +66,7 @@ getOutputValues <- function(simulationResults, quantitiesOrPaths, individualIds
 
     for (individualIndex in seq_along(individualIds)) {
       individualId <- individualIds[individualIndex]
-      vals <- simulationResults$getValuesByPath(path = path, individualIds = individualId)
-      if (is.null(vals)) {
-        next
-      }
+      vals <- simulationResults$getValuesByPath(path = path, individualIds = individualId, stopIfNotFound)
```
Comment (msevestre) [inline R/utilities-simulation-results.R]: e.g. here you could do the check. AT that stage, you only have to deal with na no?

File: R/utilities-entity.R [hunk 6]
```diff
@@ -70,3 +77,78 @@ unify <- function(groupEntitiesByPathFunc, paths) {
...
+#' # Returns all `Volume` parameters defined in `Organism` and all its subcontainers
+#' params <- getAllParametersMatching("Organism|**|Volume", sim)
+#' @export
+getAllEntitiesMatching <- function(paths, container, entityType) {
+  # Test for correct inputs
+  validateIsOfType(container, c(Simulation, Container))
+  validateIsString(paths)
+
+  className <- entityType$classname
+  if(length(which(names(ContainerTasks) == className)) == 0){
```
Comment (msevestre) [inline R/utilities-entity.R]: Use `validateEnumValue` ?

File: R/simulation-results.R (hunk 2 above)
Comment (PavelBal) [reply R/simulation-results.R]: Are we going to have one method for getting simulation results, or two - `getOutputValues` and `getOutputValuesTLF`? If it will be only one, I will put the check into one of them. Otherwise having the check here avoids duplication of code.

Comment (msevestre) [reply R/simulation-results.R]: Can't answer that yet. Ideally only one but  who knows
