### PR TITLE
Fixes #222 $print method of Quantity and QuantitySelection failing

### LINKED ISSUE #222: $print method of Quantity and QuantitySelection failing
`private$printLine(self$path, getQuantityTypesStringFromInt(self$quantityType))`

should read 

`private$printLine(self$path,getQuantityTypeAsString(self$quantityType))`

Also write tests covering the $print-methods of our classes.

### PR DESCRIPTION
**Pull request by PavelBal**

### CODE REVIEW

File: tests/testthat/test-container.R [hunk 1]
```diff
@@ -45,3 +45,8 @@ test_that("It throws an error when trying to set the name of a container", {
   container <- getContainer(liverPath, sim)
   expect_that(container$name <- "name", throws_error())
 })
+
+test_that("It can print container", {
+  container <- getContainer(liverPath, sim)
+  expect_error(container$print(), NA)
```
Comment (msevestre) [inline tests/testthat/test-container.R]: Expect error?? This reads weird. Can you explain?

Comment (PavelBal) [reply tests/testthat/test-container.R]: `expect_error(someCall, NA)` is the way to test for no error being generated in testthat.

Comment (msevestre) [reply tests/testthat/test-container.R]: Ok weird
