### PR TITLE
Fixes #158 $print of OutputSelections does not show the observer type

### LINKED ISSUE #158: $print of OutputSelections does not show the observer type
```
OutputSelections : 
  Organism|PeripheralVenousBlood|Caffeine|Plasma (Peripheral Venous Blood): 
  Organism|ArterialBlood|Plasma|Caffeine|Concentration in container: 
  Organism|ArterialBlood|Plasma|Caffeine|Plasma Unbound: 
  Organism|ArterialBlood|BloodCells|Caffeine|Concentration in container: 
  Organism|ArterialBlood|Caffeine|Whole Blood: 
  Organism|LargeIntestine|Plasma|Caffeine: Drug
  Organism|Kidney|Plasma|Caffeine: Drug
  Organism|SmallIntestine|Plasma|Caffeine: Drug
  Organism|Brain|Plasma|Caffeine: Drug
  Organism|Skin|Plasma|Caffeine: Drug
  Organism|ArterialBlood|Plasma|Caffeine: Drug
  Organism|Bone|Plasma|Caffeine: Drug
  Organism|PortalVein|Plasma|Caffeine: Drug
  Organism|VenousBlood|Plasma|Caffeine: Drug
  Organism|Lung|Plasma|Caffeine: Drug
  Organism|Stomach|Plasma|Caffeine: Drug
  Organism|Fat|Plasma|Caffeine: Drug
  Organism|Spleen|Plasma|Caffeine: Drug
  Organism|Pancreas|Plasma|Caffeine: Drug
  Organism|Heart|Plasma|Caffeine: Drug
  Organism|Gonads|Plasma|Caffeine: Drug
  Organism|Muscle|Plasma|Caffeine: Drug
  Organism|Liver|Volume: Parameter
```

Empty space after `:` for the observer outputs. @msevestre I suppose it is a wrong definition in the enum `QuantityType`?

### PR DESCRIPTION
**Pull request by PavelBal**

### CODE REVIEW

File: R/quantity-type.R [hunk 1]
```diff
@@ -14,3 +14,12 @@ QuantityType <- enum(list(
   Parameter = bitwShiftL(2, 8),
   Time = bitwShiftL(2, 9)
 ))
+
```
Comment (PavelBal) [inline R/quantity-type.R]: Not sure this is elegant, but it works.

Comment (msevestre) [reply R/quantity-type.R]: Can you please add tests for this?

File: R/quantity-type.R [hunk 2]
```diff
@@ -14,3 +14,12 @@ QuantityType <- enum(list(
...
   Time = bitwShiftL(2, 9)
 ))
+
+getQuantityTypesStringFromInt <- function(quantityInt){
+  quantityTypes <- intToBits(quantityInt)
+  quantityTypes <- which(as.logical(quantityTypes))
+  quantityTypes <- bitwShiftL(2, quantityTypes-2)
+  quantityTypes <- lapply(quantityTypes, getEnumKey, QuantityType)
+
+  return(quantityTypes)
```
Comment (msevestre) [inline R/quantity-type.R]: I would rename this function to getQuantityTypeAsString and return the string instead of the list. Comsumer will always have to paste and collapse which is not ergnomic

File: R/quantity-type.R [hunk 3]
```diff
@@ -14,3 +14,12 @@ QuantityType <- enum(list(
   Parameter = bitwShiftL(2, 8),
   Time = bitwShiftL(2, 9)
 ))
+
+getQuantityTypesStringFromInt <- function(quantityInt){
+  quantityTypes <- intToBits(quantityInt)
+  quantityTypes <- which(as.logical(quantityTypes))
+  quantityTypes <- bitwShiftL(2, quantityTypes-2)
```
Comment (msevestre) [inline R/quantity-type.R]: What does that all do here? Can you explain? (best is exlain as comment in the code)

File: R/quantity-type.R (hunk 2 above)
Comment (PavelBal) [reply R/quantity-type.R]: Done.

File: R/quantity-type.R (hunk 3 above)
Comment (PavelBal) [reply R/quantity-type.R]: Added comments.

File: R/quantity-type.R (hunk 1 above)
Comment (PavelBal) [reply R/quantity-type.R]: Tests added
