### PR TITLE
`.unitConverter()` doesn't convert geometric error

### LINKED ISSUE #1044: unitConverter should not try to convert error values if the error is geometric
If error type is geometric, conversion of yValues to different units should not trigger conversion of error values (and units).

```
obsData <- loadDataSetFromPKML(system.file("extdata", "ObsDataAciclovir_3.pkml", package = "ospsuite"))
> .unitConverter(dataSetToDataFrame(obsData), yUnit = "µmol/l")
 Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension, : 
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit '' is not defined in dimension 'Concentration (mass)'.
Method: Double[] convertToBaseUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
Stack trace:
at OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
at OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit(String dimensionName, String displayUnit, Double[] valuesInDisplayUnit, Double molWeight)
7.
rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension, 
sourceUnit, values, molWeight) at utilities-units.R#208
6.
toUnit(quantityOrDimension = yData$yDimension[[1]], values = yData$yErrorValues, 
targetUnit = yTargetUnit, sourceUnit = yData$yErrorUnit[[1]], 
molWeight = yData$molWeight[[1]], molWeightUnit = ospUnits$`Molecular weight`$`g/mol`) at utilities-units.R#665
5.
.yErrorUnitConverter(data, yTargetUnit) at utilities-units.R#575
4.
.f(.x[[i]], ...)
3.
map(.x, .f, ...)
2.
purrr::map_dfr(.x = yErrorDataList, .f = function(data) .yErrorUnitConverter(data, 
yTargetUnit)) at utilities-units.R#575
1.
.unitConverter(dataSetToDataFrame(obsData), yUnit = "µmol/l")

```

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Closes #1044

### CODE REVIEW

File: R/utilities-units.R [hunk 1]
```diff
@@ -662,6 +662,14 @@ ospUnits <- list()
 #' @keywords internal
 #' @noRd
 .yErrorUnitConverter <- function(yData, yTargetUnit) {
+  # If error type is geometric, conversion of `yValues` to different units
+  # should not trigger conversion of error values (and units)
+  if ("yErrorType" %in% colnames(yData) &&
+    !is.na(unique(yData$yErrorType)) &&
+    unique(yData$yErrorType) == "GeometricStdDev") {
```
Comment (PavelBal) [inline R/utilities-units.R:669]: Please use the enum value `DataErrorType$GeometricStdDev`.

Comment (IndrajeetPatil) [reply R/utilities-units.R]: Done!

**Review by PavelBal — APPROVED** [review]
